version: "3"
services:
  proxy:
    container_name: "proxy"
    build: build/proxy
    ports:
      - "8080:8080"
    links:
      - "server"
  server:
    container_name: "server"
    build: build/server
    ports:
      - "9090:9090"
  web:
    container_name: "web"
    build: build/web
    ports:
      - "3000:3000"
