version: "3"
services:
  proxy:
    container_name: "proxy"
    build:
      context: .
      dockerfile: ./build/proxy/Dockerfile
    ports:
      - "8080:8080"
    links:
      - "server"
  server:
    container_name: "server"
    build:
      context: .
      dockerfile: ./build/server/Dockerfile
    ports:
      - "9090:9090"
  web:
    container_name: "web"
    build:
      context: .
      dockerfile: ./build/web/Dockerfile
    ports:
      - "3000:3000"
